{% set name = "xmod" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xmod-{{ version }}.tar.gz
  sha256: 38c76486b9d672c546d57d8035df0beb7f4a9b088bc3fb2de5431ae821444377

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core
    - pip
  run:
    - python >=3.8

test:
  imports:
    - xmod
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rec/xmod
  summary: 🌱 Turn any object into a module 🌱
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicornk
