{% set name = "xmod" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rec/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 504565c14feaef0801f3161ad4d4cefa9228f3cbcedc6e1cdf276456de87deca

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python

# E AssertionError: assert (<module 'test.modules.partial_function' from '$SRC_DIR/test/modules/partial_function.py'> and False)
# Following test is not valid for Python>3.9
{% set deselect_tests = "" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_xmod.py::TestXmod::test_partial_function" %}  # [py>39]

test:
  source_files:
    - test
  imports:
    - xmod
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v test {{ deselect_tests }}
  requires:
    - pip
    - pytest

about:
  home: https://github.com/rec/xmod
  summary: Turn any object into a module
  description: Turn any object into a module
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/rec/xmod
  doc_url: https://rec.github.io/xmod

extra:
  recipe-maintainers:
    - nicornk
