{% set name = "xmod" %}
{% set version = "1.10.0" %}
{% set deselect_tests = "" %}
{% set deselect_tests = 'deselect_tests + " --deselect=test/test_xmod.py::TestXmod::test_partial_function"' %}  # [py>39]

# E AssertionError: assert (<module 'test.modules.partial_function' from '$SRC_DIR/test/modules/partial_function.py'> and False)
# Following test is not valid for Python>3.9
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rec/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ed8b42a59ff9bcd372df0ffd10cbde717207f5ab44d6614433dd0f438ce50b36

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python

test:
  source_files:
    - test
  imports:
    - xmod
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v test {{ deselect_tests }}
  requires:
    - pip
    - pytest

about:
  home: https://github.com/rec/xmod
  summary: Turn any object into a module
  description: Turn any object into a module
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/rec/xmod
  doc_url: https://rec.github.io/xmod

extra:
  recipe-maintainers:
    - nicornk
